name: flutters_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # âœ… Tambahkan ini untuk kalkulator
  math_expressions: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Bagian ini yang sudah diperbaiki
flutter:
  uses-material-design: true

  # Tambahkan baris-baris ini
  assets:
    - assets/profil.jpeg
    - assets/rosblok.png
